### ISSUE TITLE
I am unable to create the environment variables file.

### ISSUE THREAD

**Issue by yash2879** [aknp-solutions/rms-backend#5]
_FLASK_APP = rms.py
FLASK_ENV = development
MYSQL_HOST = ****
MYSQL_USER = root
MYSQL_PASSWORD = *******
MYSQL_PORT = 8088
MYSQL_UNIX_SOCKET = MySQL	
MYSQL_CONNECT_TIMEOUT = 10_

this is what I created based on my understanding, as I didn't understand what other parameters do....

it gives this error:

 * Serving Flask app '= rms.py' (lazy loading)
 * Environment: = development
 * Debug mode: off
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: Could not import '= rms'.

**Comment by advaithm582** [comment]
Try removing the space between the = and the value. For example,
```
FLASK_APP=rms.py
FLASK_ENV=development
MYSQL_USER=aknp_rms
```
And name the file as .flaskenv
It should be in the outermost directory.
